food = [
    {
        "Name": "Cereal",
        "Calor": 105,
        "SS": "1 cup",
        "Total": 1.9,
        "Chol": 0,
        "Sod": 139,
        "Carb": 21,
        "Fiber": 2.6,
        "Sugar": 1.2,
        "Protein": 3.4,
        "Iron": 3.4,
        "Pot": 3.4,
        "Calc": 42,

    },
    {
        "Name": "Pancakes",
        "Calor": 149.4,
        "SS": "1 6 inch pancake",
        "Total": 1.9,
        "Chol": 9.2,
        "Sod": 483.6,
        "Carb": 28.3,
        "Fiber": 1,
        "Sugar": 16,
        "Protein": 4,
        "Iron": 1.2,
        "Pot": 134.8,
        "Calc": 97,

    },
    {
        "Name": "Bagels",
        "Calor": 291.9,
        "SS": "1 bagel: 3.5 to 4 inches",
        "Total": 2.2,
        "Chol": 25.2,
        "Sod": 530.3,
        "Carb": 55.7,
        "Fiber": 2.4,
        "Sugar": 6,
        "Protein": 11.1,
        "Iron": 4.2,
        "Pot": 71.4,
        "Calc": 13.7,

    },
    {
        "Name": "Eggs",
        "Calor": 78,
        "SS": "1 Egg",
        "Total": 5,
        "Chol": 187,
        "Sod": 62,
        "Carb": 0.6,
        "Fiber": 0,
        "Sugar": 0.6,
        "Protein": 6,
        "Iron": 0.6,
        "Pot": 63,
        "Calc": 25,

    },
    {
        "Name": "French Toast",
        "Calor": 125.7,
        "SS": "1 piece",
        "Total": 3.6,
        "Chol": 48.4,
        "Sod": 292.1,
        "Carb": 18.9,
        "Fiber": 0.6,
        "Sugar": 4,
        "Protein": 4.4,
        "Iron": 1.3,
        "Pot": 79.1,
        "Calc": 63.1,

    },
    {
        "Name": "Toast",
        "Calor": 75.1,
        "SS": "1 slice",
        "Total": 1,
        "Chol": 1,
        "Sod": 144.2,
        "Carb": 13.4,
        "Fiber": 1.1,
        "Sugar": 1.5,
        "Protein": 3.1,
        "Iron": 1,
        "Pot": 3.1,
        "Calc": 39.6,

    },
    {
        "Name": "Waffles",
        "Calor": 99.8,
        "SS": "1 waffle",
        "Total": 3.4,
        "Chol": 4.9,
        "Sod": 223.3,
        "Carb": 15,
        "Fiber": 0.8,
        "Sugar": 3.3,
        "Protein": 2.3,
        "Iron": 2,
        "Pot": 2.3,
        "Calc": 107.8,

    },
    {
        "Name": "Plain Oatmeal",
        "Calor": 150,
        "SS": "1/2 Cup of Oatmeal",
        "Total": 3.6,
        "Chol": 0,
        "Sod": 278,
        "Carb": 29,
        "Fiber": 4.8,
        "Sugar": 1,
        "Protein": 5.1,
        "Iron": 1.2,
        "Pot": 128.8,
        "Calc": 14.4,

    },
    {
        "Name": "Yogurt",
        "Calor": 100,
        "SS": "1 cup",
        "Total": 0,
        "Chol": 0,
        "Sod": 70,
        "Carb": 7,
        "Fiber": 0,
        "Sugar": 7,
        "Protein": 18,
        "Iron": 0.1,
        "Pot": 240,
        "Calc": 187,

    },
    {
        "Name": "Bacon",
        "Calor": 45,
        "SS": "1 Serving",
        "Total": 3.5,
        "Chol": 7.5,
        "Sod": 135,
        "Carb": 0,
        "Fiber": 0,
        "Sugar": 0,
        "Protein": 2.5,
        "Iron": 0,
        "Pot": 42.5,
        "Calc": 1,

    },
    {
        "Name": "Ham Sandwich",
        "Calor": 210,
        "SS": "1 Serving",
        "Total": 4,
        "Chol": 12,
        "Sod": 770,
        "Carb": 35,
        "Fiber": 3,
        "Sugar": 3,
        "Protein": 11,
        "Iron": 2.08,
        "Pot": 0,
        "Calc": 113.12,

    },
    {
        "Name": "Veggie Salad",
        "Calor": 22,
        "SS": "2 Cups of Salad",
        "Total": 0.22,
        "Chol": 0,
        "Sod": 30,
        "Carb": 4.65,
        "Fiber": 1.6,
        "Sugar": 2.66,
        "Protein": 1.1,
        "Iron": 0.41,
        "Pot": 240,
        "Calc": 31,

    },
    {
        "Name": "Chicken Salad",
        "Calor": 254,
        "SS": "0.5 cups",
        "Total": 18,
        "Chol": 64,
        "Sod": 226,
        "Carb": 3.3,
        "Fiber": 0.4,
        "Sugar": 2.4,
        "Protein": 19,
        "Iron": 1.1,
        "Pot": 208,
        "Calc": 37,

    },
    {
        "Name": "Hamburger",
        "Calor": 540,
        "SS": "1 sandwich",
        "Total": 27,
        "Chol": 122,
        "Sod": 791,
        "Carb": 40,
        "Fiber": 1.3,
        "Sugar": 11.06,
        "Protein": 34,
        "Iron": 3.5,
        "Pot": 570,
        "Calc": 122,

    },
    {
        "Name": "Beef Burrito (Beef, Beans, & Cheese)",
        "Calor": 628,
        "SS": "1 Burrito",
        "Total": 32.92,
        "Chol": 95,
        "Sod": 1083,
        "Carb": 48.12,
        "Fiber": 8.1,
        "Sugar": 1.93,
        "Protein": 34.32,
        "Iron": 5.05,
        "Pot": 612,
        "Calc": 452,

    },
    {
        "Name": "Cheese Pizza",
        "Calor": 270,
        "SS": "1 slice",
        "Total": 13,
        "Chol": 21,
        "Sod": 462,
        "Carb": 26.8,
        "Fiber": 1.6,
        "Sugar": 3.06,
        "Protein": 10.6,
        "Iron": 1.6,
        "Pot": 168,
        "Calc": 181,

    },
    {
        "Name": "Peanut Butter and Jelly Sandwich",
        "Calor": 378,
        "SS": "1 sandwich",
        "Total": 18,
        "Chol": 0,
        "Sod": 405,
        "Carb": 46,
        "Fiber": 3.4,
        "Sugar": 15,
        "Protein": 12,
        "Iron": 1.8,
        "Pot": 269,
        "Calc": 20,

    },
    {
        "Name": "Grilled Cheese Sandwich",
        "Calor": 366,
        "SS": "1 sandwich",
        "Total": 23,
        "Chol": 63,
        "Sod": 886,
        "Carb": 28,
        "Fiber": 1.4,
        "Sugar": 5.4,
        "Protein": 12,
        "Iron": 0.2,
        "Pot": 185,
        "Calc": 284.3,

    },
    {
        "Name": "Hot Dog",
        "Calor": 250,
        "SS": "1 frankfurter on bun",
        "Total": 14.98,
        "Chol": 24,
        "Sod": 717,
        "Carb": 18.9,
        "Fiber": 0.8,
        "Sugar": 2.29,
        "Protein": 9.06,
        "Iron": 1.77,
        "Pot": 116,
        "Calc": 56,

    },
    {
        "Name": "Burrito",
        "Calor": 434,
        "SS": "1 burrito",
        "Total": 16,
        "Chol": 29,
        "Sod": 1087,
        "Carb": 56,
        "Fiber": 1.2,
        "Sugar": 5.1,
        "Protein": 17,
        "Iron": 4.5,
        "Pot": 492,
        "Calc": 113,

    },
    {
        "Name": "Sushi",
        "Calor": 74,
        "SS": "2 rolls",
        "Total": 0.22,
        "Chol": 2,
        "Sod": 310,
        "Carb": 15.55,
        "Fiber": 0.4,
        "Sugar": 3.26,
        "Protein": 2.24,
        "Iron": 0.71,
        "Pot": 67,
        "Calc": 10,

    },
    {
        "Name": "Beef Taco (Cheese, Lettuce, Tomato & Sour Cream)",
        "Calor": 304,
        "SS": "1 Taco",
        "Total": 16.33,
        "Chol": 46,
        "Sod": 680,
        "Carb": 23.91,
        "Fiber": 1.6,
        "Sugar": 1.44,
        "Protein": 14.66,
        "Iron": 2.32,
        "Pot": 246,
        "Calc": 182,

    },
    {
        "Name": "Garlic Bread",
        "Calor": 151,
        "SS": "1 slice presliced",
        "Total": 7.1,
        "Chol": 0,
        "Sod": 234,
        "Carb": 18,
        "Fiber": 1.1,
        "Sugar": 1.6,
        "Protein": 3.6,
        "Iron": 1.8,
        "Pot": 44,
        "Calc": 16,
    },
    {
        "Name": "Tomato Soup",
        "Calor": 170,
        "SS": "1 bowl",
        "Total": 1.1,
        "Chol": 0,
        "Sod": 910,
        "Carb": 36,
        "Fiber": 2.6,
        "Sugar": 20,
        "Protein": 3.5,
        "Iron": 0.59,
        "Pot": 1342,
        "Calc": 13,

    },
    {
        "Name": "Veggie Fried Rice",
        "Calor": 279,
        "SS": "1 cup",
        "Total": 14,
        "Chol": 88,
        "Sod": 363,
        "Carb": 30,
        "Fiber": 2.1,
        "Sugar": 2.2,
        "Protein": 8,
        "Iron": 1,
        "Pot": 206,
        "Calc": 20,

    },
    {
        "Name": "White Rice",
        "Calor": 205,
        "SS": "1 cup",
        "Total": 0.4,
        "Chol": 0,
        "Sod": 1.6,
        "Carb": 45,
        "Fiber": 0.6,
        "Sugar": 0.1,
        "Protein": 4.3,
        "Iron": 0.3,
        "Pot": 55,
        "Calc": 16,

    },
    {
        "Name": "Whole Grain Rice",
        "Calor": 109,
        "SS": "0.5 cups",
        "Total": 0.8,
        "Chol": 0,
        "Sod": 1,
        "Carb": 23,
        "Fiber": 1.8,
        "Sugar": 0.7,
        "Protein": 2.3,
        "Iron": 0.8,
        "Pot": 77,
        "Calc": 20,

    },
    {
        "Name": "Pesto Pasta",
        "Calor": 384,
        "SS": "1 cup",
        "Total": 25.66,
        "Chol": 10,
        "Sod": 179,
        "Carb": 28.66,
        "Fiber": 2.4,
        "Sugar": 1.07,
        "Protein": 11.27,
        "Iron": 2.43,
        "Pot": 170,
        "Calc": 160,

    },
    {
        "Name": "Baked Salmon",
        "Calor": 468,
        "SS": "1 fillet",
        "Total": 28,
        "Chol": 143,
        "Sod": 138,
        "Carb": 0,
        "Fiber": 0,
        "Sugar": 0,
        "Protein": 50,
        "Iron": 0.34,
        "Pot": 872,
        "Calc": 30,

    },
    {
        "Name": "Pork Burrito Bowl",
        "Calor": 230,
        "SS": "1 Large Bowl",
        "Total": 6,
        "Chol": 25,
        "Sod": 480,
        "Carb": 33,
        "Fiber": 4,
        "Sugar": 3,
        "Protein": 12,
        "Iron": 3.6,
        "Pot": 756,
        "Calc": 60,

    },
    {
        "Name": "Veg Burrito Bowl",
        "Calor": 702,
        "SS": "1 bowl",
        "Total": 24,
        "Chol": 134,
        "Sod": 1390,
        "Carb": 74,
        "Fiber": 8.2,
        "Sugar": 5.4,
        "Protein": 47,
        "Iron": 1,
        "Pot": 1150,
        "Calc": 340,

    },
    {
        "Name": "Minestrone Soup",
        "Calor": 233,
        "SS": "1 cup",
        "Total": 12.6,
        "Chol": 9,
        "Sod": 698,
        "Carb": 21.74,
        "Fiber": 3.8,
        "Sugar": 3.64,
        "Protein": 8.98,
        "Iron": 2.11,
        "Pot": 588,
        "Calc": 82,

    },
    {
        "Name": "Black Bean Soup",
        "Calor": 253,
        "SS": "1 cup",
        "Total": 6.3,
        "Chol": 2.5,
        "Sod": 765,
        "Carb": 36,
        "Fiber": 12,
        "Sugar": 2.2,
        "Protein": 13,
        "Iron": 7,
        "Pot": 836,
        "Calc": 23,

    },
    {
        "Name": "Black Bean Burger",
        "Calor": 476,
        "SS": "1 burger on bun",
        "Total": 9.9,
        "Chol": 49,
        "Sod": 394,
        "Carb": 75,
        "Fiber": 7.5,
        "Sugar": 6.2,
        "Protein": 23,
        "Iron": 4,
        "Pot": 818,
        "Calc": 106,

    },
    {
        "Name": "Butter Noodles",
        "Calor": 298,
        "SS": "1 cup",
        "Total": 13,
        "Chol": 31,
        "Sod": 92,
        "Carb": 38,
        "Fiber": 38,
        "Sugar": 0.7,
        "Protein": 7.3,
        "Iron": 1.44,
        "Pot": 58,
        "Calc": 19.95,

    },
    {
        "Name": "Chicken Alfredo Pasta",
        "Calor": 1191,
        "SS": "2 cups",
        "Total": 81,
        "Chol": 282,
        "Sod": 940,
        "Carb": 71,
        "Fiber": 3.7,
        "Sugar": 4.7,
        "Protein": 46,
        "Iron": 1.1,
        "Pot": 440,
        "Calc": 250,

    },
    {
        "Name": "Mac n' Cheese",
        "Calor": 376,
        "SS": "1 cup",
        "Total": 16,
        "Chol": 5.9,
        "Sod": 669,
        "Carb": 47,
        "Fiber": 2.4,
        "Sugar": 8.5,
        "Protein": 9.7,
        "Iron": 2.2,
        "Pot": 225,
        "Calc": 161,

    },
    {
        "Name": "Lemonade",
        "Calor": 99,
        "SS": "1 cup",
        "Total": 0.1,
        "Chol": 0,
        "Sod": 9.9,
        "Carb": 26,
        "Fiber": 0,
        "Sugar": 25,
        "Protein": 0.2,
        "Iron": 0.4,
        "Pot": 37,
        "Calc": 10,

    },
    {
        "Name": "Cranberry Juice",
        "Calor": 137,
        "SS": 0.25,
        "Total": 0.25,
        "Chol": 0,
        "Sod": 5,
        "Carb": 34.21,
        "Fiber": 0,
        "Sugar": 30.03,
        "Protein": 0,
        "Iron": 0.25,
        "Pot": 195,
        "Calc": 8,

    },
    {
        "Name": "Apple Juice",
        "Calor": 114,
        "SS": "1 cup",
        "Total": 0.3,
        "Chol": 0,
        "Sod": 9.9,
        "Carb": 28,
        "Fiber": 0.5,
        "Sugar": 24,
        "Protein": 0.3,
        "Iron": 0.3,
        "Pot": 250,
        "Calc": 20,

    },
    {
        "Name": "Orange Juice",
        "Calor": 112,
        "SS": "1 cup",
        "Total": 0.5,
        "Chol": 0,
        "Sod": 2,
        "Carb": 25.79,
        "Fiber": 0.5,
        "Sugar": 20.83,
        "Protein": 1.74,
        "Iron": 0.5,
        "Pot": 496,
        "Calc": 27,

    },
    {
        "Name": "Potato Chips",
        "Calor": 149,
        "SS": "1 oz",
        "Total": 9.5,
        "Chol": 0,
        "Sod": 148,
        "Carb": 15,
        "Fiber": 0.9,
        "Sugar": 0.1,
        "Protein": 1.8,
        "Iron": 0.5,
        "Pot": 335,
        "Calc": 7,

    },
    {
        "Name": "French Fries",
        "Calor": 156,
        "SS": "1/2 Cup",
        "Total": 8.01,
        "Chol": 0,
        "Sod": 171,
        "Carb": 20.33,
        "Fiber": 1.9,
        "Sugar": 0.33,
        "Protein": 1.98,
        "Iron": 0.69,
        "Pot": 300,
        "Calc": 7,

    },
    {
        "Name": "Cheez its",
        "Calor": 150,
        "SS": "27 Crakers",
        "Total": 8,
        "Chol": 0,
        "Sod": 230,
        "Carb": 17,
        "Fiber": 1,
        "Sugar": 0,
        "Protein": 3,
        "Iron": 1,
        "Pot": 0,
        "Calc": 30,

    },
    {
        "Name": "Goldfish",
        "Calor": 140,
        "SS": "55 Pieces",
        "Total": 5,
        "Chol": 10,
        "Sod": 250,
        "Carb": 20,
        "Fiber": 0.9,
        "Sugar": 0,
        "Protein": 3,
        "Iron": 1.2,
        "Pot": 50,
        "Calc": 40,

    },
    {
        "Name": "Oreos",
        "Calor": 160,
        "SS": "3 Cookies",
        "Total": 7,
        "Chol": 0,
        "Sod": 0,
        "Carb": 25,
        "Fiber": 1,
        "Sugar": 14,
        "Protein": 1,
        "Iron": 1.4,
        "Pot": 50,
        "Calc": 10,

    },
    {
        "Name": "Tortilla Chips",
        "Calor": 146,
        "SS": "10 Chips",
        "Total": 7.01,
        "Chol": 0,
        "Sod": 126,
        "Carb": 19.6,
        "Fiber": 1.6,
        "Sugar": 0.3,
        "Protein": 2.34,
        "Iron": 0.7,
        "Pot": 2.34,
        "Calc": 52,

    },
    {
        "Name": "Strawberries",
        "Calor": 49,
        "SS": "1 Cup",
        "Total": 0.46,
        "Chol": 0,
        "Sod": 2,
        "Carb": 11.67,
        "Fiber": 3,
        "Sugar": 7.08,
        "Protein": 1.02,
        "Iron": 0.64,
        "Pot": 233,
        "Calc": 24,

    },
    {
        "Name": "Blueberries",
        "Calor": 83,
        "SS": "1 Cup",
        "Total": 0.48,
        "Chol": 0,
        "Sod": 1,
        "Carb": 21.01,
        "Fiber": 3.5,
        "Sugar": 14.44,
        "Protein": 1.07,
        "Iron": 0.41,
        "Pot": 112,
        "Calc": 9,

    },
    {
        "Name": "Grapes",
        "Calor": 34,
        "SS": "1 cup",
        "Total": 0.26,
        "Chol": 0,
        "Sod": 3,
        "Carb": 28.96,
        "Fiber": 1.4,
        "Sugar": 24.77,
        "Protein": 1.15,
        "Iron": 0.58,
        "Pot": 306,
        "Calc": 16,

    },
    {
        "Name": "Vanilla Ice Cream",
        "Calor": 145,
        "SS": "1/2 Cup",
        "Total": 7.92,
        "Chol": 32,
        "Sod": 58,
        "Carb": 16.99,
        "Fiber": 0.5,
        "Sugar": 15.28,
        "Protein": 2.52,
        "Iron": 0.06,
        "Pot": 131,
        "Calc": 92,

    },
    {
        "Name": "Chocolate Ice Cream",
        "Calor": 287,
        "SS": "1 Cup",
        "Total": 14.63,
        "Chol": 45,
        "Sod": 101,
        "Carb": 37.51,
        "Fiber": 1.6,
        "Sugar": 33.73,
        "Protein": 5.05,
        "Iron": 1.24,
        "Pot": 331,
        "Calc": 145,
    },
]